[package]
name = "tnb"
version = "0.1.0"
authors = ["wint3rmute <mateusz.baczek1998@gmail.com>"]
edition = "2018"
description = "command | tnb - pipe your commands to your Telegram Notifications Bot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
rust-ini = "0.13"
dirs = "2.0.2"

